// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class DebugNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 480
    let windowHeight: Int = 480

    // MARK: - Window Title
    let windowTitle: String = "Dev Tools (Debug)"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_debug.png"
    let imageWidth: Int = 220
    let imageHeight: Int = 220
}
